# Example: show the connected Bluetooth device on the status bar.

set -g @plugin 'gufranco/tmux-bluetooth-revamped'

set -g @bluetooth_revamped_icon 'BT'

set -g status-right '#{bluetooth_icon} #{bluetooth} '
